### ISSUE TITLE
can't merge my post2

### ISSUE THREAD

**Issue by suzume300** [suzume300/sendagi_plus#5]
```
Run withastro/action@v1
Run len=`echo $INPUT_PM | wc -c`
Run actions/setup-node@v3
Found in cache @ /opt/hostedtoolcache/node/18.19.0/x64
Environment details
/opt/hostedtoolcache/node/18.19.0/x64/bin/npm config get cache
/home/runner/.npm
npm cache is not found
Run cd .

added [5](https://github.com/suzume300/sendagi_plus/actions/runs/7368889930/job/20053997207#step:3:6)43 packages, and audited 544 packages in 9s

2[38](https://github.com/suzume300/sendagi_plus/actions/runs/7368889930/job/20053997207#step:3:40) packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
Run cd .

> build
> astro build

 error   `astro sync` command failed to generate content collection types: can not read a block mapping entry; a multiline key may not be an implicit key
  Hint:
    Check your `src/content/config.*` file for typos.
  File:
    /home/runner/work/sendagi_plus/sendagi_plus/node_modules/astro/dist/core/sync/index.js:77:11
  Code:
    76 |     }
    > 77 |     throw new AstroError(
         |           ^
      78 |       {
      79 |         ...AstroErrorData.GenerateContentTypesError,
      80 |         message: AstroErrorData.GenerateContentTypesError.message(safeError.message)
  Stacktrace:
GenerateContentTypesError: `astro sync` command failed to generate content collection types: can not read a block mapping entry; a multiline key may not be an implicit key
    at syncInternal (file:///home/runner/work/sendagi_plus/sendagi_plus/node_modules/astro/dist/core/sync/index.js:77:11)
    at async AstroBuilder.setup (file:///home/runner/work/sendagi_plus/sendagi_plus/node_modules/astro/dist/core/build/index.js:79:21)
    at async AstroBuilder.run (file:///home/runner/work/sendagi_plus/sendagi_plus/node_modules/astro/dist/core/build/index.js:1[50](https://github.com/suzume300/sendagi_plus/actions/runs/7368889930/job/20053997207#step:3:53):23)
    at async build (file:///home/runner/work/sendagi_plus/sendagi_plus/node_modules/astro/dist/core/build/index.js:37:3)
    at async build (file:///home/runner/work/sendagi_plus/sendagi_plus/node_modules/astro/dist/cli/build/index.js:20:3)
    at async runCommand (file:///home/runner/work/sendagi_plus/sendagi_plus/node_modules/astro/dist/cli/index.js:110:7)
    at async cli (file:///home/runner/work/sendagi_plus/sendagi_plus/node_modules/astro/dist/cli/index.js:148:5)

Error: Process completed with exit code 1.
```

**Comment by sorami** [comment]
#4 と同様
